from __future__ import annotations

import json
from pathlib import Path

import pytest
import requests
from pactman import Consumer, Like, Provider

from services.core.marketplace.contracts import ConsentScope


@pytest.fixture(scope="session")
def marketplace_pact(pact_directory: Path) -> Path:
    """Generate the consumer contract for marketplace integrations."""

    pact = Consumer("bmad-web").has_pact_with(
        Provider("core-marketplace"),
        pact_dir=str(pact_directory),
        version="3.0.0",
    )

    catalogue_body = [
        {
            "id": "smart-pricing",
            "name": "Smart Pricing AI",
            "description": "Automated pricing updates using ML-driven demand forecasts.",
            "categories": ["Revenue", "Automation"],
            "icon_url": None,
            "contractVersion": "2024-05-01",
            "sandboxOnly": False,
        },
        {
            "id": "housekeeping-pro",
            "name": "Housekeeping Pro",
            "description": "Optimize housekeeping routes and staffing via predictive insights.",
            "categories": ["Operations", "Automation"],
            "icon_url": "https://cdn.bmad.io/marketplace/housekeeping-pro.svg",
            "contractVersion": "2024-04-18",
            "sandboxOnly": False,
        },
        {
            "id": "payments-360",
            "name": "Payments 360",
            "description": "Unified ledger, reconciliation, and payouts automation.",
            "categories": ["Finance", "Compliance"],
            "icon_url": None,
            "contractVersion": "2024-03-30",
            "sandboxOnly": True,
        },
    ]

    contract_body = {
        "version": "2024-05-01",
        "summary": "AI powered pricing suggestions with revenue share billing",
        "scopes": [ConsentScope.BOOKINGS.value, ConsentScope.ANALYTICS.value],
        "webhookEndpoints": ["https://smart-pricing.example/hooks/pricing"],
        "rateLimitPerMinute": 90,
        "sandboxRequired": True,
    }

    sandbox_body = {
        "sandboxId": Like("sandbox-env-123"),
        "expiresAt": Like("2024-07-01T00:00:00.000Z"),
        "credentials": Like({"client_id": "abc", "client_secret": "xyz"}),
    }

    payload = {
        "workspaceId": "staging-workspace",
        "scopes": [ConsentScope.BOOKINGS.value, ConsentScope.ANALYTICS.value],
        "grantedBy": "qa@bmad.io",
        "sandboxRequested": True,
        "correlationId": "contract-suite",
    }

    (
        pact.given("published marketplace catalogue")
        .upon_receiving("a request to list marketplace apps")
        .with_request("get", "/marketplace/apps")
        .will_respond_with(200, body=catalogue_body)
    )

    (
        pact.given("smart pricing contract is available")
        .upon_receiving("a request for smart pricing contract details")
        .with_request("get", "/marketplace/apps/smart-pricing/contract")
        .will_respond_with(200, body=contract_body)
    )

    (
        pact.given("sandbox requested for smart pricing")
        .upon_receiving("a sandbox installation request")
        .with_request("post", "/marketplace/apps/smart-pricing/install", body=payload)
        .will_respond_with(202, body=sandbox_body)
    )

    with pact:
        base_url = pact.uri
        catalogue_response = requests.get(f"{base_url}/marketplace/apps", timeout=5)
        assert catalogue_response.status_code == 200
        assert catalogue_response.json() == catalogue_body

        contract_response = requests.get(
            f"{base_url}/marketplace/apps/smart-pricing/contract",
            timeout=5,
        )
        assert contract_response.status_code == 200
        assert contract_response.json() == contract_body

        install_response = requests.post(
            f"{base_url}/marketplace/apps/smart-pricing/install",
            json=payload,
            timeout=5,
        )
        assert install_response.status_code == 202

    return pact_directory / "bmad-web-core-marketplace-pact.json"


def test_marketplace_provider_matches_contract(
    marketplace_pact: Path,
    marketplace_client,
) -> None:
    """Validate that the FastAPI provider honours the generated pact."""

    assert marketplace_pact.exists(), "Pact file was not generated by the consumer suite"

    contract = json.loads(marketplace_pact.read_text(encoding="utf-8"))

    for interaction in contract.get("interactions", []):
        request = interaction["request"]
        response = interaction["response"]
        method = request["method"].lower()
        path = request["path"]
        body = request.get("body")
        client_response = marketplace_client.request(method, path, json=body)

        assert client_response.status_code == response["status"], (
            f"Unexpected status for {method.upper()} {path}: "
            f"expected {response['status']} got {client_response.status_code}"
        )

        expected_body = response.get("body")
        if expected_body:
            payload = client_response.json()
            if path.endswith("/install"):
                # Dynamic values must respect the contract shape
                assert payload["sandboxId"], "sandboxId should be issued"
                assert payload["expiresAt"], "expiresAt must be returned"
                credentials = payload.get("credentials", {})
                assert credentials.get("client_id"), "Sandbox credential client_id missing"
                assert credentials.get("client_secret"), "Sandbox credential client_secret missing"
            else:
                assert payload == expected_body
