apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app.kubernetes.io/name: identity
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: identity
  template:
    metadata:
      labels:
        app.kubernetes.io/name: identity
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: identity
          image: ghcr.io/bmad-method/identity:dev
          ports:
            - containerPort: 8100
          env:
            - name: CORE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: identity-app
                  key: CORE_DATABASE_URL
            - name: CORE_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: identity-app
                  key: CORE_ALLOWED_ORIGINS
            - name: CORE_TENANCY_PLATFORM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: identity-app
                  key: CORE_TENANCY_PLATFORM_TOKEN
            - name: CORE_AUTH_SESSION_TIMEOUT_SECONDS
              valueFrom:
                secretKeyRef:
                  name: identity-app
                  key: CORE_AUTH_SESSION_TIMEOUT_SECONDS
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8100
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
