repository:
  name: Bmad-Method-v3
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  squash_merge_commit_title: COMMIT_OR_PR_TITLE
  squash_merge_commit_message: COMMIT_MESSAGES
  branch_protection_rule:
    required_conversation_resolution: true
  pull_request_template: .github/pull_request_template.md
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_signatures: true
      required_linear_history: true
      enforce_admins: true
      required_status_checks:
        strict: true
        checks:
          - context: CI
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 2
        require_code_owner_reviews: true
        require_last_push_approval: true
      restrictions: null
  - name: develop
    protection:
      required_signatures: true
      required_linear_history: true
      enforce_admins: true
      required_status_checks:
        strict: true
        checks:
          - context: CI
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
        require_code_owner_reviews: true
      restrictions: null

collaborators: []
team_permission: []
