version: 2

models:
  - name: silver_reservations
    description: "Camada silver com enriquecimento e métricas de reservas."
    columns:
      - name: reservation_id
        tests:
          - not_null
          - unique
      - name: stay_length_nights
        tests:
          - not_null
      - name: realized_revenue
        tests:
          - not_null
  - name: silver_bundle_usage
    description: "Camada silver com conversão e latência dos bundles."
    columns:
      - name: bundle_id
        tests:
          - not_null
      - name: period_start
        tests:
          - not_null
      - name: conversion_rate
        tests:
          - not_null
