name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  build:
    name: Lint and Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.4.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_BASH: true

      - name: Run Unit Tests
        run: ./scripts/test-unit.sh

      - name: Run Integration Tests
        run: ./scripts/test-integration.sh

      - name: Upload Placeholder Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation-plan
          path: docs/
